# Site settings
title: "Ocarina"
email: hello@wearekick.co.uk


# Directories
source:       ./docs
destination:  ./_site
layouts_dir:  _layouts
includes_dir: _includes

# Handling Reading
safe:         false
include:      []
exclude:      []
keep_files:
  - stylesheets/ocarina.css
  - stylesheets/ocarina.map.css
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
detach:  false
baseurl: "" # does not include hostname
show_dir_listing: false
